project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: images/favicon.ico
  twitter-card:
    title: Health Data Science Datathon 2024 | UNSW Faculty of Medicine and Health
    description: A two-day datathon where teams will work together to analyse real-world infectious disease monitoring data. Participants will develop a full data science pipeline with prizes awarded for the best submission.
  open-graph:
    title: Health Data Science Datathon 2024 | UNSW Faculty of Medicine and Health
    description: A two-day datathon where teams will work together to analyse real-world infectious disease monitoring data. Participants will develop a full data science pipeline with prizes awarded for the best submission.
  image: "https://quarto.org/quarto-dark-bg.jpeg"
  back-to-top-navigation: true
  navbar:
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: Schedule
        icon: clock
        href: schedule.qmd
      - text: Data
        icon: code
        href: data.qmd
      - text: Judging Criteria
        icon: trophy
        href: judging-criteria.qmd
      - text: Code of conduct
        icon: heart
        href: code-of-conduct.qmd
      - text: Past datathons
        icon: calendar2-heart
        menu:
          - text: '2023'
            icon: capsule-pill
            href: review.qmd
    right:
      - text: Information for sponsors
        icon: info-circle
        href: sponsor-info.qmd

  page-footer:
    center: © UNSW 2024

format:
  html:
    theme: [cyborg, custom.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true



